APIGOV-26571 - Update current discovery process as needed
Axway/agents-kong pull request #19
Opened 2023-11-01 13:18 UTC by alrosca

Updated spec discovery to use pre-configured spec paths

2023-11-01 13:45 UTC, dgghinea approved these changes

2023-11-01 14:25 UTC, jcollins-axway commented on pkg/config/discovery/config.go
> +	SpecHomePath         string   `config:"specHomePath"`
this can be cleaned

2023-11-01 14:28 UTC, jcollins-axway commented on pkg/gateway/client.go
> +		ctx:            context.Background(),
I do not think we want to set the context on this structure, since it is long lived. Usually we only add it to a structure that is short lived, like the executioners in our embedded agents.

2023-11-01 14:29 UTC, jcollins-axway commented on pkg/gateway/client.go
> +	services, err := gc.kongClient.ListServices(gc.ctx)
rather than use gc.ctx here create a ctx at the top of this func and change the signature of processKongServicesList to receive a ctx

2023-11-01 14:30 UTC, jcollins-axway commented on pkg/gateway/client.go
>  	logger := logrus.WithFields(logrus.Fields{
can we change this to use the sdk log pacakge

2023-11-01 14:31 UTC, jcollins-axway commented on pkg/gateway/client.go
> +	gc.logger.Infof("processing service %s", *service.Name)
maybe set the service name as a field on the logger here rather than adding to the message

2023-11-01 17:09 UTC, jcollins-axway commented on pkg/gateway/client.go
> +	gc.logger.Infof("processing service %s", *service.Name)
setting the fields in the logger can be repeated in other places in here too

2023-11-01 17:11 UTC, jcollins-axway commented on pkg/kong/kongclient.go
> +		"package":   "discovery",
these look incorrect, and the sdk logger please

2023-11-01 17:24 UTC, jcollins-axway commented on pkg/kong/kongclient.go
> +	defer cancel()
Should this be created before each call rather than before all calls? Meaning will it cancel prior to all paths being queried?

2023-11-01 17:25 UTC, jcollins-axway commented on pkg/processor/eventmapper.go
> +	"github.com/Axway/agent-sdk/pkg/transaction/util"
I think Gabe and I both imported this as sdkUtil

2023-11-01 17:25 UTC, jcollins-axway requested changes
comments added

2023-11-02 13:49 UTC, jcollins-axway commented on pkg/gateway/client.go
> +	gc.logger.Infof("processing service %s", *service.Name)
> maybe set the service name as a field on the logger here rather than adding to the message

@alrosca I think you may have missed this one, setting fields on the logger rather than adding them in formatted messages

2023-11-02 13:50 UTC, jcollins-axway commented on pkg/kong/kongclient.go
> +	logger := log.NewFieldLogger().WithComponent("discovery").WithPackage("kong")
component is client?

2023-11-02 13:52 UTC, jcollins-axway commented
could you update the default_kong_discovery_agent.yml file in root with the removed and added config settings?

2023-11-02 14:08 UTC, jcollins-axway commented on pkg/gateway/client.go
> +	gc.logger.Infof("processing service %s", *service.Name)
I take this back, partially, the service name is in a field. There are a few other fields that can be moved there, route ID and service host are the ones I see. Then we do not need to add them to the message, just have the message such as "processing service" since the name is in the field.

2023-11-02 14:10 UTC, alrosca commented on pkg/gateway/client.go
> +	gc.logger.Infof("processing service %s", *service.Name)
Sounds good, will do, thanks :D

2023-11-03 15:40 UTC, jcollins-axway approved these changes

2023-11-03 15:43 UTC, merged