APIGOV-26780 - acl plugin changes
Axway/agents-kong pull request #50
Opened 2023-12-06 09:12 UTC by dgghinea

2023-12-06 14:04 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
What is the difference between hasACLEnabledInPluginsMap and hasACLEnabledInPlugins?

Whichever is used can be changed to return just a boolean and the caller, when hasACL... is false can log the warning.

2023-12-06 14:06 UTC, jcollins-axway commented on pkg/discovery/subscription/access/access.go
> +		return rs.SetMessage("Access request provisioning not required due to missing ACL plugin.").Success(), nil
no need to add the message here, just return success

2023-12-06 14:06 UTC, jcollins-axway commented on pkg/discovery/subscription/access/access.go
> +		return rs.SetMessage("Access request deprovisioning not required due to missing ACL plugin.").Success()
same as above, message not needed

2023-12-06 14:08 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
I see the difference between the 2. I think we only need the existing one. If that one is not found then we do not set it at all on access requests. We should not need to check on each api being discovered.

2023-12-06 14:09 UTC, jcollins-axway requested changes
see comments for changes requested

2023-12-06 14:16 UTC, dgghinea commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
The access request adds the id of the consumer to the ACL plugin from the route found in the received request. I believe there could be routes that have an ACL enabled (while a global ACL is disabled) ?

2023-12-06 14:19 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
The call "kongClient.Plugins.ListAll(context.Background())" returns all plugins used regardless of it being global or scoped. So the initial check not having any ACL means no routes would ever have any. Once we fail this we will not manage any ACLs.

2023-12-06 14:21 UTC, dgghinea commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
Yes, but in the case of it returning success, it still does not guarantee that all the routes have an ACL installed.

2023-12-06 14:23 UTC, dgghinea commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
or should the initial check look for a globally enabled ACL ?

2023-12-06 14:23 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
And the access request handling will add it if it is not there.

2023-12-06 14:25 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
Maybe, rather than determining if the agent will manage the acls for access requests we let the user configure if the agent should. If they have the ACL management configured we look for the global acl, as you suggested, and the agent will manage adding and removing acls to the routes as needed.

2023-12-06 14:26 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
If they decide to not manage acls we do no checks and no handling with the access requests

2023-12-06 14:27 UTC, dgghinea commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
> And the access request handling will add it if it is not there.

oh, you're right. my bad

2023-12-06 14:28 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
> Maybe, rather than determining if the agent will manage the acls for access requests, we let the user configure if the agent should. If they have the ACL management configured we look for the global acl, as you suggested, and the agent will manage adding and removing acls to the routes as needed.

looks like that is what the ticket suggested any way

2023-12-06 16:01 UTC, dgghinea commented on pkg/discovery/gateway/client.go
> +func hasACLEnabledInPluginsMap(plugins map[string]*klib.Plugin) error {
yep, you're right

2023-12-06 17:02 UTC, vivekschauhan approved these changes

2023-12-07 14:08 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +	}
I think we can clean this logic a little.

```
err = hasGlobalACLEnabledInPlugins(plugins, agentConfig.KongGatewayCfg.ACL.Required)
if err != nil {
  return nil, err
}
...

return &Client{
...
  hasACL: agentConfig.KongGatewayCfg.ACL.Required
}, nil


...
func hasGlobalACLEnabledInPlugins(plugins []*klib.Plugin, aclRequired bool) error {
  if !aclRequired {
    log.Warn(...)
    return nil
  }
  ... // rest of func
}
```

2023-12-07 14:08 UTC, jcollins-axway commented on pkg/discovery/gateway/client.go
> +		common.AttrHasACL:    gc.hasACL,
is this still needed?

2023-12-07 16:30 UTC, jcollins-axway commented on pkg/discovery/config/config.go
> +	cfgKongACLRequired       = "kong.acl.required"
This new setting will need an update to the tests

2023-12-07 16:47 UTC, jcollins-axway commented on pkg/discovery/config/config.go
> +	cfgKongACLRequired       = "kong.acl.required"
Can we do the opposite and make this kong.acl.disabled then by default had it required? Similar to how the ports.http.disabled is used?

2023-12-08 10:16 UTC, dgghinea commented on pkg/discovery/config/config.go
> +	cfgKongACLRequired       = "kong.acl.required"
> This new setting will need an update to the tests

not sure about this. Whether or not it is disabled, there's no change to the config validation output. It only impacts when the gateway is hit.

2023-12-08 14:53 UTC, jcollins-axway commented on helm/kong-agents/templates/discovery-deployment.yaml
>              - name: KONG_PROXY_PORTS_HTTP
This and the HTTPS var names need updated here and in the traceability-statefulset.yaml file

2023-12-08 14:57 UTC, jcollins-axway commented on pkg/discovery/subscription/access/access.go
> +		a.logger.Info("ACL plugin is disabled or not existing for current spec. Skipping access request deprovisioning")
This can be moved to debug

2023-12-08 16:08 UTC, merged